import {
  ArrowRight, Check, CheckCircle2, ClipboardList, Eye, FileWarning,
  LockKeyhole, MapPin, MessageCircle, Phone, ShieldCheck, UserRoundCheck,
} from "lucide-react";
import { Container } from "./Container";
import { SectionHeading } from "./SectionHeading";
import { ConsultationForm } from "./ConsultationForm";
import { dashboardItems, industries, processSteps, readinessItems, services } from "@/data/content";

export function Hero() {
  return <section id="top" className="bg-[#f8fafc] py-16 sm:py-20 lg:py-24">
    <Container className="grid items-center gap-14 lg:grid-cols-[1.08fr_.92fr]">
      <div>
        <p className="flex max-w-xl items-center gap-2 border-l-2 border-[#d4a72c] pl-3 text-xs font-bold uppercase tracking-[.08em] leading-5 text-[#0f766e]"><ShieldCheck size={15} className="shrink-0" />Practical Data Protection Support for Ghanaian Organisations</p>
        <h1 className="mt-6 max-w-3xl font-[var(--font-manrope)] text-[clamp(2.25rem,3.8vw,3.5rem)] font-extrabold leading-[1.1] tracking-[-.035em] text-[#0b1f33]">Protect personal data. Strengthen trust. Build stronger compliance practices.</h1>
        <p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">DataGuard Ghana helps organisations understand their data protection responsibilities, identify privacy risks and implement practical compliance measures that fit their operations.</p>
        <div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#contact" className="btn btn-primary">Request a Data Protection Assessment <ArrowRight size={18} /></a><a href="#services" className="btn btn-secondary">Explore Our Services</a></div>
        <p className="mt-5 flex items-center gap-2 text-sm font-semibold text-slate-600"><CheckCircle2 size={17} className="text-[#0f766e]" />Clear guidance. Practical documentation. Ongoing support.</p>
      </div>
      <div className="border border-slate-300 bg-white" aria-label="Illustrative data protection assessment scope">
        <div className="border-t-4 border-[#0f766e] px-5 py-5 sm:px-7"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#0f766e]">Assessment scope</p><div className="mt-2 flex items-end justify-between gap-4"><h2 className="text-xl font-bold text-[#0b1f33]">Data Protection Readiness</h2><span className="text-xs font-medium text-slate-500">Sample assessment scope</span></div></div>
        <div className="border-y border-slate-200 px-5 sm:px-7">{dashboardItems.map((item, i) => <div key={item} className="grid grid-cols-[2rem_1fr] items-center gap-3 border-b border-slate-100 py-3.5 last:border-b-0"><span className="font-[var(--font-manrope)] text-xs font-bold text-[#0f766e]">{String(i + 1).padStart(2, "0")}</span><span className="text-sm font-semibold text-slate-700">{item}</span></div>)}</div>
        <div className="bg-[#f8fafc] px-5 py-5 sm:px-7"><div className="flex items-center justify-between gap-4 text-sm"><span className="font-bold text-[#0b1f33]">Compliance readiness review</span><span className="text-xs text-slate-500">Example workflow</span></div><div className="mt-4 grid grid-cols-4 gap-1" aria-label="Four-stage illustrative review process"><span className="h-1.5 bg-[#0f766e]" /><span className="h-1.5 bg-[#0f766e]" /><span className="h-1.5 bg-slate-300" /><span className="h-1.5 bg-slate-300" /></div><div className="mt-2 grid grid-cols-4 gap-1 text-[.62rem] font-semibold uppercase tracking-wide text-slate-500"><span>Discover</span><span>Review</span><span>Prioritise</span><span>Plan</span></div><p className="mt-4 text-xs leading-5 text-slate-500">This illustrates the review process. It is not a visitor score or indication of regulatory approval.</p></div>
      </div>
    </Container>
  </section>;
}

export function TrustStrip() {
  const items = [[MapPin,"Ghana-focused guidance"],[ClipboardList,"Practical implementation"],[LockKeyhole,"Confidential assessments"],[UserRoundCheck,"Support for growing organisations"]] as const;
  return <section className="border-y border-slate-200 bg-white" aria-label="Our commitments"><Container className="grid grid-cols-2 lg:grid-cols-4">{items.map(([Icon,label], i) => <div key={label} className={`flex items-center gap-2 border-b border-slate-100 py-4 text-xs font-bold leading-5 text-[#0b1f33] sm:gap-3 sm:text-sm lg:border-b-0 lg:px-5 ${i % 2 ? "border-l pl-3 sm:pl-5" : "pr-3"}`}><Icon size={18} className="shrink-0 text-[#0f766e]" />{label}</div>)}</Container></section>;
}

export function ComplianceChallenge() {
  const cards = [
    [Eye, "Unclear responsibilities", "Many organisations collect personal data without clearly assigning responsibility for how it is obtained, used, stored, shared and deleted."],
    [FileWarning, "Missing documentation", "Privacy notices, internal policies, consent records, processing registers and incident procedures are often incomplete or unavailable."],
    [UserRoundCheck, "Limited staff awareness", "Employees may handle personal data every day without sufficient training on confidentiality, security and data subject rights."],
  ] as const;
  return <section id="about" className="section-pad bg-white"><Container><SectionHeading label="Why data protection matters" title="Personal data exists in almost every part of your organisation." copy="Customer records, employee files, CVs, student information, financial records, CCTV footage, health details, phone numbers and email addresses are all forms of personal data. Without the right controls, organisations may face privacy complaints, security incidents, operational disruption and loss of public trust." /><div className="mt-12 grid gap-8 md:grid-cols-3">{cards.map(([Icon,title,copy]) => <article className="border-t-2 border-[#0f766e] pt-6" key={title}><Icon className="text-[#0f766e]" size={22} /><h3 className="mt-5 text-xl font-bold text-[#0b1f33]">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{copy}</p></article>)}</div><p className="mt-10 border-l-4 border-[#d4a72c] pl-5 text-lg font-bold leading-8 text-[#0b1f33]">Data protection should not be treated as paperwork alone. It should become part of everyday operations.</p></Container></section>;
}

export function ProcessSection() {
  return <section id="process" className="section-pad bg-[#f8fafc]"><Container><SectionHeading label="Our approach" title="A practical path from awareness to ongoing compliance" /><div className="relative mt-12 grid gap-8 lg:grid-cols-4"><div className="absolute left-[12%] right-[12%] top-6 hidden h-px bg-slate-300 lg:block" aria-hidden="true" />{processSteps.map(({number,title,description,deliverables,icon:Icon}) => <article key={title} className="relative"><span className="relative z-10 grid size-12 place-items-center border border-slate-300 bg-white text-[#0b1f33]"><Icon size={22} /></span><p className="mt-6 text-xs font-extrabold tracking-widest text-[#0f766e]">{number}</p><h3 className="mt-1 text-2xl font-bold text-[#0b1f33]">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{description}</p><ul className="mt-5 grid gap-2">{deliverables.map(item => <li key={item} className="flex gap-2 text-sm text-slate-700"><Check size={16} className="mt-0.5 shrink-0 text-[#0f766e]" />{item}</li>)}</ul></article>)}</div></Container></section>;
}

export function ServicesSection() {
  return <section id="services" className="section-pad bg-white"><Container><SectionHeading label="Services" title="Data protection support designed around your operations" /><div className="mt-12 grid border-t border-slate-300 md:grid-cols-2">{services.map(({title,description}, index) => <article key={title} className="grid grid-cols-[2.25rem_1fr] gap-4 border-b border-slate-200 py-7 md:px-7 md:odd:border-r md:odd:pl-0"><span className="pt-1 font-[var(--font-manrope)] text-xs font-extrabold tracking-wider text-[#0f766e]">{String(index + 1).padStart(2, "0")}</span><div><h3 className="text-lg font-bold leading-6 text-[#0b1f33]">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{description}</p></div></article>)}</div><p className="mt-8 border-l-2 border-[#d4a72c] pl-4 text-sm font-semibold text-[#0b1f33]">Services are tailored to the size, sector, risk level and operational needs of each organisation.</p></Container></section>;
}

export function IndustriesSection() {
  return <section id="industries" className="section-pad bg-[#f8fafc]"><Container><SectionHeading label="Who we support" title="Built for organisations that handle valuable personal information" /><div className="mt-12 grid gap-px overflow-hidden border border-slate-200 bg-slate-200 md:grid-cols-2 lg:grid-cols-3">{industries.map(({title,description,icon:Icon,featured}) => <article key={title} className={`p-6 ${featured ? "bg-[#0b1f33] text-white lg:col-span-2 lg:grid lg:grid-cols-[1fr_auto] lg:gap-10" : "bg-white"}`}><div>{featured && <p className="mb-5 text-xs font-bold uppercase tracking-[.14em] text-[#e4bd51]">Primary sector focus</p>}<Icon size={24} className={featured ? "text-[#e4bd51]" : "text-[#0f766e]"} /><h3 className={`mt-5 text-xl font-bold ${featured ? "text-white" : "text-[#0b1f33]"}`}>{title}</h3><p className={`mt-3 text-sm leading-7 ${featured ? "max-w-2xl text-slate-300" : "text-slate-600"}`}>{description}</p></div>{featured && <a href="#contact" className="mt-6 inline-flex items-center gap-2 self-end text-sm font-bold text-white hover:text-[#e4bd51] lg:mt-0">Discuss an assessment <ArrowRight size={17} /></a>}</article>)}</div><a href="#contact" className="btn btn-primary mt-9">Discuss Your Organisation’s Needs <ArrowRight size={18} /></a></Container></section>;
}

export function WhyDataGuard() {
  const benefits = [["Local context","Our approach reflects how Ghanaian organisations operate and the realities they face when building data protection practices."],["Practical implementation","We go beyond explaining requirements by helping organisations turn recommendations into working procedures and documents."],["Right-sized support","Recommendations are prioritised according to the organisation’s size, risks, resources and stage of compliance maturity."],["Long-term improvement","We help organisations develop repeatable practices instead of relying on one-time compliance exercises."]] as const;
  return <section className="section-pad bg-[#0b1f33]"><Container><SectionHeading light label="Why DataGuard Ghana" title="Practical guidance your organisation can put into operation" /><div className="mt-12 grid border-y border-white/15 sm:grid-cols-2">{benefits.map(([title,copy], i) => <article key={title} className="border-b border-white/15 py-7 sm:px-7 sm:odd:border-r"><span className="text-xs font-bold tracking-widest text-[#e4bd51]">0{i+1}</span><h3 className="mt-3 text-xl font-bold text-white">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-300">{copy}</p></article>)}</div><blockquote className="mt-10 max-w-4xl border-l-4 border-[#d4a72c] pl-6 font-[var(--font-manrope)] text-xl font-semibold leading-9 text-white">“Our goal is to help organisations protect people’s information while building stronger, more trusted operations.”</blockquote></Container></section>;
}

export function ReadinessChecklist() {
  return <section className="section-pad bg-white"><Container className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><SectionHeading label="Readiness assessment" title="How ready is your organisation?" copy="Your organisation may need a data protection review if any of the following statements apply." /><a href="#contact" className="btn btn-primary mt-7">Book a Readiness Assessment <ArrowRight size={18} /></a></div><div className="border-y border-slate-300 py-6"><ul className="grid gap-4">{readinessItems.map(item => <li key={item} className="flex gap-3 text-sm leading-6 text-slate-700"><span className="mt-0.5 grid size-5 shrink-0 place-items-center border border-emerald-300 bg-emerald-50"><Check size={13} className="text-[#0f766e]" /></span>{item}</li>)}</ul><p className="mt-6 border-t border-slate-200 pt-5 text-xs leading-5 text-slate-500">An assessment helps identify priorities. It is not a guarantee of regulatory approval or complete legal compliance.</p></div></Container></section>;
}

export function ContactSection() {
  return <section id="contact" className="section-pad bg-[#f1f5f9]"><Container className="grid gap-12 lg:grid-cols-[.78fr_1.22fr]"><div><SectionHeading label="Request a consultation" title="Start strengthening your organisation’s data protection practices" copy="Tell us about your organisation and the support you need. We will use the information to prepare for an initial discussion." /><address className="mt-8 grid gap-4 not-italic"><a href="tel:+233245052539" className="flex items-center gap-3 font-semibold text-[#0b1f33] hover:text-[#0f766e]"><Phone size={20} className="text-[#0f766e]" />Phone and WhatsApp: +233 24 505 2539</a><p className="flex items-center gap-3 text-slate-700"><MapPin size={20} className="text-[#0f766e]" />Location: Ghana</p><p className="flex items-center gap-3 text-slate-700"><MessageCircle size={20} className="text-[#0f766e]" />Service delivery: On-site and remote support</p><a href="mailto:enquiry@dataguardghana.com" className="flex items-center gap-3 text-slate-700 hover:text-[#0f766e]"><span className="grid size-5 place-items-center text-[#0f766e]">@</span>enquiry@dataguardghana.com</a></address></div><ConsultationForm /></Container></section>;
}
